select info.id,
       info.PROTOCOLNUMBER,
       info.PROTOCOLNAME,
       info.PROTOCOLDATE,
       info.CONCLUSION,
       info.METHODNAME,
       info.APPROVEDBYFULLNAME,
       info.APPROVEDBYPOSITION,
       info.PROTOCOLSCANNAME,
       info.INDICATOR,
       info.MEASURINGRANGES,
       info.NORMATIVEDOCUMENT,
       info.NORMATIVEVALUE,
       info.STARTDATE,
       info.ENDDATE,
       customer.CUSTOMERTYPE,
       customer.FULLNAME,
       customer.INN,
       customer.TEL,
       customer.EMAIL,
       customer.CRTFNUMBER,
       customer.CRTFDATESTART,
       customer.CRTFDATEEND,
       customer.CRTFOGRN,
       customer.CRTFDECLARERNAME,
       customer.CRTFDECLARERTEL,
       customer.CRTFDECLAREREMAIL,
       customer.ULNAME,
       customer.ULSHORTNAME,
       customer.ULOGRN,
       customer.IPOGRNIP,
       customer.FLPASSPORTSERIES,
       customer.FLPASSPORTNUMBER,
       customer.FLPASSPORTISSUEDBY,
       customer.FLPASSPORTISSUEDATE,
       customer.FLPASSPORTSUBCODE,
       customer.FLPASSPORTNOTEXIST,
       customer.FLDOCUMENT,
       customer.FULNAME,
       customer.FULADDRESS,
       customer.AFULNAME,
       customer.MSI_NAME,
       labinfo.CERTIFICATENUM,
       labinfo.LABORATORYNAME,
       labinfo.ACCREDITATIONDATE,
       labinfo.ACCREDITATIONEXPDATE,
       labinfo.HEADFULLNAME,
       labinfo.PHONE,
       labinfo.EMAIL,
       info_researcher.FIO,
       info_researcher.POSITION,
       info_researcher.REGISTR_NUMBER,
       production.KINDID,
       production.NAME,
       production.INFO,
       production.SELECTIONMETHOD,
       production.RECEIPTDATE,
       production.OBJECTTEST,
       production.PURPOUSETEST,
       production.DESCRIPTIONPURPOSE,
       address.ADDRESS

FROM FSA_RPI.info
         LEFT JOIN FSA_RPI.customer ON fsa_rpi.info.reportid = fsa_rpi.customer.reportid
         LEFT JOIN FSA_RPI.production ON fsa_rpi.info.reportid = fsa_rpi.production.reportid
         LEFT JOIN FSA_RPI.info_researcher ON fsa_rpi.info.id = fsa_rpi.info_researcher.id_info
         LEFT JOIN FSA_RPI.labinfo ON fsa_rpi.info.reportid = fsa_rpi.labinfo.reportid
         LEFT JOIN FSA_RPI.ADDRESS ON fsa_rpi.labinfo.address_id = fsa_rpi.address.id
where FSA_RPI.info.PROTOCOLDATE BETWEEN '01.01.2021' AND '31.01.2021'
ORDER BY FSA_RPI.info.protocoldate;
